version: '3.8'

services:
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile.strapi
    volumes:
      - ./uploads:/srv/app/public/uploads
      - ./extensions:/srv/app/extensions
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: password
      NODE_ENV: development

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strapi

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile.nextjs
    environment:
      NEXT_PUBLIC_STRAPI_API_URL: 'http://localhost/api'
    depends_on:
      - strapi

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - strapi
      - nextjs
